### ISSUE TITLE
Exporting an Amira image resulted in a runtime error

### ISSUE THREAD

**Issue by del-archer** [parallaxinnovations/MicroView#40]
M/V version = 2.5.0-3446
OS = Windows Home, version 1607, build 14393.576

When I attempted to export an Amira file (see zip file below) as a series of 2D images, there was a runtime error and nothing was exported (nor was there any other indicator that it failed).

Log entries:
`[2017-01-11T15:14:57] [ERROR]:  MicroViewIO
Traceback (most recent call last):
  File "C:\cygwin\home\jerem_000\src\MV\Lib\site-packages\PI\visualization\MicroView\MicroViewIO.py", line 1481, in ExportImage
  File "C:\cygwin\home\jerem_000\src\MV\Lib\site-packages\PI\visualization\vtkMultiIO\vtkMultiImageWriter.py", line 285, in Write
  File "c:\progra~1\parall~1\microv~1\plugins\vtkmultiio_standard-2.5.0.post3446-py2.7.egg\vtkMultiIOStandard\vtkDICOMImageWriter.py", line 120, in Write
    full_array.shape = inp.GetDimensions()[::-1]
ValueError: total size of new array must be unchanged`

[testvector2c.zip](https://github.com/parallaxinnovations/MicroView/files/699960/testvector2c.zip)

**Comment by jeremy-gill** [comment]
Multi-channel images aren't supported by the DICOM infrastructure; I've added a more sensible exception message and will need to add code to the export chain to remove DICOM from the list of available writers.
