### ISSUE TITLE
Opening a Windows Bitmap file fails

### ISSUE THREAD

**Issue by del-archer** [parallaxinnovations/MicroView#41]
M/V version = 2.5.0-3446
OS = Windows Home, version 1607, build 14393.576

When I attempted to open a Windows Bitmap file (see zip file below), MicroView threw a runtime error:

```
Traceback (most recent call last):
  File "C:\cygwin\home\jerem_000\src\MV\Lib\site-packages\PI\visualization\MicroView\MicroViewIO.py", line 524, in OpenImageFile
  File "C:\cygwin\home\jerem_000\src\MV\Lib\site-packages\PI\visualization\vtkMultiIO\vtkMultiImageReader.py", line 536, in SetFileName
  File "c:\progra~1\parall~1\microv~1\plugins\vtkmultiio_standard-2.5.0.post3446-py2.7.egg\vtkMultiIOStandard\vtkPILImageReader.py", line 132, in SetFileName
    self.LoadImages()
  File "c:\progra~1\parall~1\microv~1\plugins\vtkmultiio_standard-2.5.0.post3446-py2.7.egg\vtkMultiIOStandard\vtkPILImageReader.py", line 156, in LoadImages
    ss.write(s)
TypeError: unicode argument expected, got 'str'
```

[markers.zip](https://github.com/parallaxinnovations/MicroView/files/700045/markers.zip)

**Comment by jeremy-gill** [comment]
The attached file is a png rather than a bmp.  It loads okay if the file extension is changed; otherwise MicroView reports an error indicating that its an unknown file type.
